  version: 2
  updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
        interval: "weekly"
      assignees:
        - "dcarbone"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
      assignees:
          - "dcarbone"
